import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

// Service Worker for Playbook Lite v1.0
// Strategy: Smart Pre-caching for Day 1-5 + Cache First for Audio
// Status: OPTIMIZED FOR CLEAN .MP3 FILES & WORKBOX MANIFEST

const CACHE_NAME = 'playbook-assets-v2-CLEAN';

// 1. CLEANUP & MANIFEST INJECTION
cleanupOutdatedCaches();

// This handles the App Shell (JS, CSS, Index.html) generated by Vite
// eslint-disable-next-line no-undef
precacheAndRoute(self.__WB_MANIFEST);

// 2. AUDIO CACHING STRATEGY (Workbox Route)
// Matches clean .mp3 files and caches them in 'playbook-assets-v2-CLEAN'
registerRoute(
  ({ request }) => request.url.endsWith('.mp3'),
  new CacheFirst({
    cacheName: CACHE_NAME,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// 3. MANUAL INSTALL: PRE-CACHE CRITICAL AUDIO
// Ensures Day 1-5 and System Audio are available immediately
const PRECACHE_AUDIO_URLS = [
  // System Audio
  '/assets/audio/system/welcome_generic.mp3',
  '/assets/audio/system/success_high.mp3',
  '/assets/audio/system/success_medium.mp3',
  '/assets/audio/system/try_again.mp3',
  '/assets/audio/system/locked_message.mp3',
];

// Helper to generate curriculum paths for Day 1-5
const languages = ['en', 'sw', 'fr'];
const phases = ['sponge', 'echo', 'hunter', 'hero'];
const phaseMap = {
  sponge: 'sound',
  echo: 'word',
  hunter: 'phrase',
  hero: 'hero',
};

languages.forEach(lang => {
  for (let i = 1; i <= 5; i++) {
    phases.forEach(phase => {
      const mappedPhase = phaseMap[phase] || phase;
      const filename = `day${i}_${mappedPhase}.mp3`;
      PRECACHE_AUDIO_URLS.push(`/assets/audio/${lang}/${filename}`);
    });
  }
});

self.addEventListener('install', (event) => {
  console.log('[SW] Installing... Pre-caching critical audio assets.');
  event.waitUntil(
    caches.open(CACHE_NAME).then(async (cache) => {
      const cachePromises = PRECACHE_AUDIO_URLS.map(async (url) => {
        try {
          // Check if already cached
          const match = await cache.match(url);
          if (match) return;

          const response = await fetch(url);
          if (response.ok) {
            return cache.put(url, response);
          } else {
             console.warn(`[SW] Failed to fetch ${url} (Status: ${response.status})`);
          }
        } catch (error) {
          console.warn(`[SW] Network error caching ${url} - Skipping.`);
        }
      });

      await Promise.all(cachePromises);
      console.log('[SW] Audio pre-caching complete.');
    })
  );
  self.skipWaiting();
});

// 4. ACTIVATE: Cleanup Old Custom Caches (v1)
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames.map((cache) => {
          // Delete old 'playbook-assets-v1' or mismatching custom caches
          // Preserves 'playbook-assets-v2-CLEAN' and Workbox internal caches
          if (cache !== CACHE_NAME && !cache.includes('workbox-precache')) {
            console.log('[SW] Deleting old cache:', cache);
            return caches.delete(cache);
          }
        })
      );
    })
  );
  self.clients.claim();
});
